import { HashMap, HashSet } from "./hashMap.js";

console.log("Implement HashMap");
const test = HashMap();
test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
test.set("kite", "pink");
test.set("lion", "golden");
console.log(test.length());
test.set("moon", "silver");
console.log(test.length());
console.log(test.showBuckets());
test.set("moon", "grey");
console.log(test.length());
console.log(test.showBuckets());
console.log(test.get("carrot"));
console.log(test.has("dog"));
console.log(test.remove("moon"));
console.log(test.length());
console.log(test.showBuckets());
console.log(test.keys());
console.log(test.values());
console.log(test.entries());
test.clear();
console.log(test.length());
console.log(test.showBuckets());

console.log("");
console.log("Implement HashSet");
const hashSet = HashSet();
hashSet.set("apple", "red");
hashSet.set("banana", "yellow");
hashSet.set("carrot", "orange");
hashSet.set("dog", "brown");
hashSet.set("elephant", "gray");
hashSet.set("frog", "green");
hashSet.set("grape", "purple");
hashSet.set("hat", "black");
hashSet.set("ice cream", "white");
hashSet.set("jacket", "blue");
hashSet.set("kite", "pink");
hashSet.set("lion", "golden");

console.log(hashSet.length());
hashSet.set("moon", "silver");
console.log(hashSet.length());
console.log(hashSet.showBuckets());
hashSet.set("moon", "grey");
console.log(hashSet.length());
console.log(hashSet.showBuckets());
console.log(hashSet.get("carrot"));
console.log(hashSet.has("dog"));
console.log(hashSet.remove("moon"));
console.log(hashSet.length());
console.log(hashSet.showBuckets());
console.log(hashSet.keys());
console.log(hashSet.entries());
hashSet.clear();
console.log(hashSet.length());
console.log(hashSet.showBuckets());
